name: Go

on:
  push:
    branches: [ master,dev ]     
  pull_request:
    branches: [ master,dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1
      with: {}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Make build
      run: make build
      
    - name: Make build
      run: make docker-build
