== Karness.io crd operator
Launch harness/conformance/end-to-end tests inside environment close to production (dev, stage…).

Operator handles api described in `core.karness.io` group

* https://drive.google.com/file/d/1cKkQtw_X11LQzafxFbDL-hl0LfhGSbnZ/view[Blueprint]
* https://drive.google.com/file/d/1j8H1Pk63lUd4tcCukLWgyFd5kdJRlWgs/view?usp=sharing[Specification]

=== Description
Perform harness tests directly inside k8s cluster via http, grpc(reflection) calls emulating specific behaviour of target system on launched scenario and checking responses.

Operator can extract some response variables inside status storage and use it during further requests.

For example, you can ask one service to create game token, and use this token further


=== API
* scenario

==== Scenario

===== spec
== spec.variables

Initial pollution of environment storage. Used to populate via `gotempalte`  body request or competition checks.

== spec.events
Step representation. Only one step should be called at the time. It describes what action is required at that moment and how check that that action was meat our completion goal

=== spec.events[].action
Request and connection flow + binding operation to our status variables storage

==== spec.events[].action.request
ToDo

==== spec.events[].action.connect
ToDo

==== spec.events[].action.bind_result
key-value opject, where key - is future variable key, value - should be `jsonpath` pattern which extracts desired value

example: `BALANCE: "{.playerdetailresponse.balance}"`

=== spec.events[].completion
==== spec.events[].completion.repeat
tell how many times we should repeat current flow for switch to next event

== Technologies

=== jsonpath
used to exstract result from send grpc/http request and put in to variable store

=== golang templates
Prepare body to send request via `variables` store and `functions`
More info: https://golang.org/pkg/text/template/#hdr-Actions

==== variables
Main feature the same as variable in your system, you just fill placeholerd with useful information which gives you possibility to make more intractable data

==== functions
Some function called inside template which more flexible then only variable as we can use power of generator, for example

.unix
return unix timestamp

.uuid
First function, no arg required, so u can simle can generate uuid string

Example: `{{ uuid }}`

.rnd_int
Return random int

.rnd_str ::len
Generate random string with specific len

Example: `{{ rnd_str 32 }}`

.range_int ::min ::max
Generate random value from range `[min, max)`
Returns error when min is greater or equal then max

.md5 ::string
calculate md5 hash of input string

.query
arts take any string slice, convert paris and return sorted and encoded query

Example: `{{squery "a" "b" "c" "d"}}`

===== Advance

  We can combine functions, `md5` function takes result of `query` which has 2 args `a` and `b`

Example: `{{ md5 (query "a" "b") }}`

  Concatenate some functions output with  existed variables and drive output to another function

Example: `{{(printf "%s%s" (query "a" "b") .HELLO ) | md5}}`

example combines result of `query` function with variable `.HELLO` and move output to `md5` function

=== Testing
https://sdk.operatorframework.io/docs/building-operators/golang/testing/[SDK]

https://book.kubebuilder.io/reference/envtest.html[builder]

https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html[builder tests writing]
On M1 important to launch test via that point
[source]
----
GOARCH=amd64 make test
----

== CRD v1beta1 support
1. `make build-v1beta1`
2. edit crd_v1beta1.yaml
a. rename v1 => v1beta1 CustomResourceDefinition's apiVersion
b. rename jsonPath => JSONPath in spec.versions[].additionalPrinterColumns
c. add new version to  `versions` slice because it's required k8s at least in 1.15 version

== ToDo
* [*] reconcile actor execute only 1 operation per reconciliation cycle
* [*] variables should be part of status
* [*] http request headers
* [*] grpcurl headers
* [*] body functions: uuid generator at least
* [ ] response mutators. for example: response extracts http url and we need to get only one of parameters
* [ ] format support: request/response not only json should be user (it could be default value), but XML also required
* [*] body should have `row` field not `json`, as we could use xml format ether
* [*] infinite or repeated actions which should finish due to some conditions
* [ ] restart approach
* [*] headers should use variable store
* [*] kv should use variable store
* [*] http path should use variable store
* [*] secrets / config maps
* [ ] event fire / listening
* [*] sets inside action could
* [*] load tests (parallel launch of N scenarios)
* [ ] templating - declare once action, repeat in any other scenario
* [*] tests checking secrets/config-maps variable usage
* [ ] var binding via regular expressions
* [*] http post form
* [*] variables per thread gives possibility perform huge extra requests (simultaneously send request to many users)
