# permissions for end users to view scenarios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scenario-viewer-role
rules:
- apiGroups:
  - core.karness.io
  resources:
  - scenarios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.karness.io
  resources:
  - scenarios/status
  verbs:
  - get
