name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1
      with: {}

    - name: Make build
      run: make build
      
    - name: Make build
      run: make docker-build
