name: Go

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@v1
      with: {}

    - name: Define vars
      env:
        IMG: d7561985/${{ github.repository }}:${{ github.ref }}
      run: echo "Docker image > ${TAG1}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Make build
      run: make build

    - name: Make docker build with tests
      run: make docker-build

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${IMG}
